/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"
	" free5gcWithOCF/src/app"
	" free5gcWithOCF/src/smf/logger"
	" free5gcWithOCF/src/smf/service"
	" free5gcWithOCF/src/smf/version"
	"github.com/sirupsen/logrus"
	"github.com/urfave/cli"
	"os"
)

var SMF = &service.SMF{}

var appLog *logrus.Entry

func init() {
	appLog = logger.AppLog
}

func main() {
	app := cli.NewApp()
	app.Name = "smf"
	fmt.Print(app.Name, "\n")
	appLog.Infoln("SMF version: ", version.GetVersion())
	app.Usage = "- free5gcWithOCFcfg common configuration file -smfcfg smf configuration file"
	app.Action = action
	app.Flags = SMF.GetCliCmd()

	if err := app.Run(os.Args); err != nil {
		logger.AppLog.Errorf("SMF Run error: %v", err)
	}
}

func action(c *cli.Context) {
	app.AppInitializeWillInitialize(c.String(" free5gcWithOCFcfg"))
	SMF.Initialize(c)
	SMF.Start()
}
