/*
 * NSSF
 *
 * Network Slice Selection Function
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"
	"free5gcWithOCF/src/app"
	"os"

	"github.com/sirupsen/logrus"
	"github.com/urfave/cli"

	"free5gcWithOCF/src/nssf/logger"
	"free5gcWithOCF/src/nssf/service"
	"free5gcWithOCF/src/nssf/version"
)

var NSSF = &service.NSSF{}

var appLog *logrus.Entry

func init() {
	appLog = logger.AppLog
}

func main() {
	app := cli.NewApp()
	app.Name = "nssf"
	fmt.Print(app.Name, "\n")
	appLog.Infoln("NSSF version: ", version.GetVersion())
	app.Usage = "-free5gchfg common configuration file -nssfcfg nssf configuration file"
	app.Action = action
	app.Flags = NSSF.GetCliCmd()

	if err := app.Run(os.Args); err != nil {
		fmt.Printf("NSSF Run error: %v", err)
	}

}

func action(c *cli.Context) {
	app.AppInitializeWillInitialize(c.String("free5gchfg"))
	NSSF.Initialize(c)
	NSSF.Start()
}
