/*
 * Nocf_Communication
 *
 * OCF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type KeyOcfType string

// List of KeyOcfType
const (
	KeyOcfType_KOCF      KeyOcfType = "KOCF"
	KeyOcfType_KPRIMEOCF KeyOcfType = "KPRIMEOCF"
)
