/*
 * Nocf_EventExposure
 *
 * OCF Event Exposure Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type ModifySubscriptionRequest struct {
	SubscriptionItemInner *OcfUpdateEventSubscriptionItemInner
	OptionItem            *OcfUpdateEventOptionItem
}
