/*
 * Nocf_Communication
 *
 * OCF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type SubscriptionData struct {
	OcfStatusUri string  `json:"ocfStatusUri"`
	OcfStatusUri string  `json:"ocfStatusUri"`
	GuamiList    []Guami `json:"guamiList,omitempty"`
}
