/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type ServiceName string

// List of ServiceName
const (
	ServiceName_NNRF_NFM                  ServiceName = "nnrf-nfm"
	ServiceName_NNRF_DISC                 ServiceName = "nnrf-disc"
	ServiceName_NUDM_SDM                  ServiceName = "nudm-sdm"
	ServiceName_NUDM_UECM                 ServiceName = "nudm-uecm"
	ServiceName_NUDM_UEAU                 ServiceName = "nudm-ueau"
	ServiceName_NUDM_EE                   ServiceName = "nudm-ee"
	ServiceName_NUDM_PP                   ServiceName = "nudm-pp"
	ServiceName_NAMF_COMM                 ServiceName = "namf-comm"
	ServiceName_NAMF_EVTS                 ServiceName = "namf-evts"
	ServiceName_NAMF_MT                   ServiceName = "namf-mt"
	ServiceName_NAMF_LOC                  ServiceName = "namf-loc"
	ServiceName_NSMF_PDUSESSION           ServiceName = "nsmf-pdusession"
	ServiceName_NSMF_EVENT_EXPOSURE       ServiceName = "nsmf-event-exposure"
	ServiceName_NAUSF_AUTH                ServiceName = "nausf-auth"
	ServiceName_NAUSF_SORPROTECTION       ServiceName = "nausf-sorprotection"
	ServiceName_NAUSF_UPUPROTECTION       ServiceName = "nausf-upuprotection"
	ServiceName_NNEF_PFDMANAGEMENT        ServiceName = "nnef-pfdmanagement"
	ServiceName_Nccf_AM_POLICY_CONTROL    ServiceName = "nccf-am-policy-control"
	ServiceName_Nccf_SMPOLICYCONTROL      ServiceName = "nccf-smpolicycontrol"
	ServiceName_Nccf_POLICYAUTHORIZATION  ServiceName = "nccf-policyauthorization"
	ServiceName_Nccf_BDTPOLICYCONTROL     ServiceName = "nccf-bdtpolicycontrol"
	ServiceName_Nccf_EVENTEXPOSURE        ServiceName = "nccf-eventexposure"
	ServiceName_Nccf_UE_POLICY_CONTROL    ServiceName = "nccf-ue-policy-control"
	ServiceName_NSMSF_SMS                 ServiceName = "nsmsf-sms"
	ServiceName_NNSSF_NSSELECTION         ServiceName = "nnssf-nsselection"
	ServiceName_NNSSF_NSSAIAVAILABILITY   ServiceName = "nnssf-nssaiavailability"
	ServiceName_NUDR_DR                   ServiceName = "nudr-dr"
	ServiceName_NLMF_LOC                  ServiceName = "nlmf-loc"
	ServiceName_N5G_EIR_EIC               ServiceName = "n5g-eir-eic"
	ServiceName_NBSF_MANAGEMENT           ServiceName = "nbsf-management"
	ServiceName_NCHF_SPENDINGLIMITCONTROL ServiceName = "nchf-spendinglimitcontrol"
	ServiceName_NCHF_CONVERGEDCHARGING    ServiceName = "nchf-convergedcharging"
	ServiceName_NNWDAF_EVENTSSUBSCRIPTION ServiceName = "nnwdaf-eventssubscription"
	ServiceName_NNWDAF_ANALYTICSINFO      ServiceName = "nnwdaf-analyticsinfo"
)
