/*
 * Nocf_Communication
 *
 * OCF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type StatusChange string

// List of StatusChange
const (
	StatusChange_UNAVAILABLE StatusChange = "OCF_UNAVAILABLE"
	StatusChange_AVAILABLE   StatusChange = "OCF_AVAILABLE"
)
