/*
 * Npcf_BDTPolicyControl Service API
 *
 * The Npcf_BDTPolicyControl Service is used by an NF service consumer to
 * retrieve background data transfer policies from the pcf and to update the pcf with
 * the background data transfer policy selected by the NF service consumer.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"
	"free5gc/src/app"
	"free5gc/src/pcf/logger"
	"free5gc/src/pcf/service"
	"free5gc/src/pcf/version"
	"os"

	"github.com/sirupsen/logrus"
	"github.com/urfave/cli"
)

var pcf = &service.pcf{}

var appLog *logrus.Entry

func init() {
	appLog = logger.AppLog
}

func main() {
	app := cli.NewApp()
	app.Name = "pcf"
	fmt.Print(app.Name, "\n")
	appLog.Infoln("pcf version: ", version.GetVersion())
	app.Usage = "-free5gpcfg common configuration file -pcfcfg pcf configuration file"
	app.Action = action
	app.Flags = pcf.GetCliCmd()

	if err := app.Run(os.Args); err != nil {
		fmt.Printf("pcf Run err: %v", err)
	}

}

func action(c *cli.Context) {
	app.AppInitializeWillInitialize(c.String("free5gpcfg"))
	pcf.Initialize(c)
	pcf.Start()
}
