/*
 * Nccf_BDTPolicyControl Service API
 *
 * The Nccf_BDTPolicyControl Service is used by an NF service consumer to
 * retrieve background data transfer policies from the CCF and to update the CCF with
 * the background data transfer policy selected by the NF service consumer.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"
	" free5gcWithOCF/src/app"
	" free5gcWithOCF/src/ccf/logger"
	" free5gcWithOCF/src/ccf/service"
	" free5gcWithOCF/src/ccf/version"
	"os"

	"github.com/sirupsen/logrus"
	"github.com/urfave/cli"
)

var CCF = &service.CCF{}

var appLog *logrus.Entry

func init() {
	appLog = logger.AppLog
}

func main() {
	app := cli.NewApp()
	app.Name = "ccf"
	fmt.Print(app.Name, "\n")
	appLog.Infoln("CCF version: ", version.GetVersion())
	app.Usage = "- free5gcWithOCFcfg common configuration file -ccfcfg ccf configuration file"
	app.Action = action
	app.Flags = CCF.GetCliCmd()

	if err := app.Run(os.Args); err != nil {
		fmt.Printf("CCF Run err: %v", err)
	}

}

func action(c *cli.Context) {
	app.AppInitializeWillInitialize(c.String(" free5gcWithOCFcfg"))
	CCF.Initialize(c)
	CCF.Start()
}
