/*
 * Nchf_BDTPolicyControl Service API
 *
 * The Nchf_BDTPolicyControl Service is used by an NF service consumer to
 * retrieve background data transfer policies from the CHF and to update the CHF with
 * the background data transfer policy selected by the NF service consumer.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"
	"free5gcWithOCF/src/app"
	"free5gcWithOCF/src/chf/logger"
	"free5gcWithOCF/src/chf/service"
	"free5gcWithOCF/src/chf/version"
	"os"

	"github.com/sirupsen/logrus"
	"github.com/urfave/cli"
)

var CHF = &service.CHF{}

var appLog *logrus.Entry

func init() {
	appLog = logger.AppLog
}

func main() {
	app := cli.NewApp()
	app.Name = "chf"
	fmt.Print(app.Name, "\n")
	appLog.Infoln("CHF version: ", version.GetVersion())
	app.Usage = "-free5gcWithOCFcfg common configuration file -chfcfg chf configuration file"
	app.Action = action
	app.Flags = CHF.GetCliCmd()

	if err := app.Run(os.Args); err != nil {
		fmt.Printf("CHF Run err: %v", err)
	}

}

func action(c *cli.Context) {
	app.AppInitializeWillInitialize(c.String("free5gcWithOCFcfg"))
	CHF.Initialize(c)
	CHF.Start()
}
